apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: CHANGEME
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "10m"

