apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        image: logankimmel/hello-go:thin
---
apiVersion: v1
kind: Service
metadata:
  name: hello-go
spec:
  selector:
    app: hello-go
  ports:
  - port: 80
    targetPort: 8080

